# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to save card stats

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"

Resources:
    PopulateCardStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: save-card-stats.default
            Runtime: nodejs10.x
            Timeout: 90
            CodeUri: ./dist/save-card-stats
            MemorySize: 128
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: api-save-card-stats
            Events:
                GetResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    PopulateCArdStatsApi:
        Description: URL to post card stats
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cardstats'
        Export:
            Name: PopulateCardStatsApi
